EXEC CrearDonante
	@folioDonante = 5678,
    @nombre = 'Juan',
    @apellidoPaterno = 'P�rez',
    @apellidoMaterno = 'Fern�ndez',
    @fechaNacimiento = '1987-06-21',
	@detalles = 'Ninguno',
    @estado = 'Nuevo Le�n',
    @municipio = 'Apodaca',
    @calle = 'Villas de Apodaca',
    @numero = 437,
    @referencias = 'En frente de la tortiller�a',
    @email = 'juanpf@gmail.com',
    @telefonoPrincipal = 8145013329,
    @telefonoSecundario = 8190036712,
    @telefonoCelular = 8149321777;

EXEC CrearDonante
	@folioDonante = 9898,
    @nombre = 'Alejandra',
    @apellidoPaterno = 'Villareal',
    @apellidoMaterno = 'Flores',
    @fechaNacimiento = '1981-10-5',
	@detalles = 'Entregar despu�s de la 1 pm',
    @estado = 'Nuevo Le�n',
    @municipio = 'Escobedo',
    @calle = 'Robles',
    @numero = 221,
    @referencias = 'Casa de tres pisos',
    @email = 'alevf@gmail.com',
    @telefonoPrincipal = 8105739445,
    @telefonoSecundario = 8115834537,
    @telefonoCelular = 8148931204;

EXEC CrearDonante
	@folioDonante = 9876,
    @nombre = 'Francisco Emiliano',
    @apellidoPaterno = 'Lopez',
    @apellidoMaterno = 'Rojas',
    @fechaNacimiento = '1990-2-11',
	@detalles = 'Entregar antes de las 10 am',
    @estado = 'Nuevo Le�n',
    @municipio = 'San Nicol�s',
    @calle = 'R�o Grande',
    @numero = 356,
    @referencias = 'Casa amarilla con un perro labrador',
    @email = 'franem@gmail.com',
    @telefonoPrincipal = 8193431098,
    @telefonoSecundario = 8100981234,
    @telefonoCelular = 8189154673;

EXEC CrearDonante
	@folioDonante = 1562,
    @nombre = 'Laura Estafania',
    @apellidoPaterno = 'Treviño',
    @apellidoMaterno = 'González',
    @fechaNacimiento = '1992-4-1',
	@detalles = 'Tocar el timbre 3 veces',
    @estado = 'Nuevo Le�n',
    @municipio = 'Escobedo',
    @calle = 'Los encinos',
    @numero = 912,
    @referencias = 'Casa roja con jardín grande',
    @email = 'lautre@gmail.com',
    @telefonoPrincipal = 8158631424,
    @telefonoSecundario = 8106842015,
    @telefonoCelular = 8190703541;

EXEC CrearDonante
	@folioDonante = 9911,
    @nombre = 'Ernesto',
    @apellidoPaterno = 'Cárdenas',
    @apellidoMaterno = 'Montero',
    @fechaNacimiento = '1979-12-5',
	@detalles = 'Qudarse a platicar unos minutos',
    @estado = 'Nuevo Le�n',
    @municipio = 'Santa Catarina',
    @calle = 'Emiliano Zapata',
    @numero = 103,
    @referencias = 'Casa azul con un naranjo en frente',
    @email = 'ernestocardenas@gmail.com',
    @telefonoPrincipal = 8188301645,
    @telefonoSecundario = 8133201254,
    @telefonoCelular = 8196563012;